[tool.black]
line-length = 100
target-version = ["py311"]
disallow-untyped-defs = true
ignore-missing-imports = true
warn-unused-imports = true

[tool.isort]
profile = "black"

[tool.sqlfluff.core]
dialect = "duckdb"
sql_file_exts = ".sql"
max_line_length = 100
large_file_skip_byte_limit = 0

[tool.mypy]
ignore_missing_imports = true
python_version = "3.11"
pretty = true
